services:
  postgres:
    image: "postgres:16.3"
    environment:
      POSTGRES_DB: beatbuddy
      POSTGRES_PASSWORD: beatbuddy
      POSTGRES_USER: beatbuddy
    ports:
      - "5432:5432"
    networks:
      - default
networks:
  default:
    name: beatbuddy-v2
