name: CI - Build and Test

on:
  pull_request:
    branches:
      - stag
    # paths:
    #   - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:14.1
    #     env:
    #       POSTGRES_USER: amigoscode
    #       POSTGRES_PASSWORD: password
    #       POSTGRES_DB: customer
    #     ports:
    #       - 5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    defaults:
      run:
        working-directory: ./**
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify
